version: '3.8'

services:
  plugin-manager:
    image: watink/plugin-manager:latest
    environment:
      - PORT=3005
      - DATABASE_URL=postgres://postgres:postgres@watink_postgres:5432/watink?sslmode=disable
      - JWT_SECRET=3123123213123
      - FRONTEND_URL=${FRONTEND_URL:-https://app.watink.com}
    networks:
      - proxy
      - watink_network
    deploy:
      mode: replicated
      replicas: 1

      
  plugin-smtp:
    image: watink/plugin-smtp:1.0.7
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - SMTP_CONCURRENCY=50
    networks:
      - watink_network
    deploy:
      mode: replicated
      replicas: 1

  engine-webchat:
    image: watink/engine-webchat:latest
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672
      - REDIS_URL=redis://redis:6379
      - PORT=3335
    networks:
      - watink_network
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

networks:
  proxy:
    external: true
  watink_network:
    external: true
