version: '3.8'

services:
  backend:
    image: whaticket-premium/backend:latest
    environment:
      - DB_DIALECT=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=whaticket
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672
      - JWT_SECRET=3123123213123
      - JWT_REFRESH_SECRET=75756756756
      - FRONTEND_URL=http://localhost
      - ENGINE_VERSION=1.0.1
      - PORT=8080
    ports:
      - "8080:8080"
    networks:
      - whaticket-premium_public
      - whaticket-premium_private
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  frontend:
    image: whaticket-premium/frontend:latest
    environment:
      - URL_BACKEND=backend:8080
      - VITE_BACKEND_URL=http://localhost:8080/
      - FRONTEND_SERVER_NAME=localhost
    ports:
      - "80:80"
    networks:
      - whaticket-premium_public
    deploy:
      mode: replicated
      replicas: 1

  whaileys-engine:
    image: whaticket-premium/engine:latest
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672
    networks:
      - whaticket-premium_private
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  rabbitmq:
    image: rabbitmq:3-management-alpine
    networks:
      - whaticket-premium_private
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 512M

  postgres:
    image: ronaldodavi/pgvectorgis:latest
    environment:
      - POSTGRES_DB=whaticket
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - whaticket-premium_private
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  whaticket-premium_public:
    driver: overlay
  whaticket-premium_private:
    driver: overlay

volumes:
  db_data:
