version: '3.8'

services:
  backend:
    image: watink/backend:1.3.97
    environment:
      - DB_DIALECT=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=watink
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672
      - JWT_SECRET=3123123213123
      - JWT_REFRESH_SECRET=75756756756
      - FRONTEND_URL=http://localhost
      - URL_BACKEND=http://localhost:8080
      - ENGINE_VERSION=1.0.85
      - PORT=8080
      - NODE_OPTIONS=--max-old-space-size=800
    ports:
      - "8080:8080"
    volumes:
      - backend_public_data:/app/public
    networks:
      - watink_public
      - watink_private
    dns:
      - 192.168.26.253
      - 8.8.8.8
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M

  frontend:
    image: watink/frontend:0.6.69
    environment:
      - URL_BACKEND=watink_backend:8080
      - VITE_BACKEND_URL=http://localhost:8080/
      - FRONTEND_SERVER_NAME=localhost
    ports:
      - "80:80"
    networks:
      - watink_public
    dns:
      - 192.168.26.253
      - 8.8.8.8
    deploy:
      mode: replicated
      replicas: 1

  whaileys-engine:
    image: watink/engine:1.0.85
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672
    networks:
      - watink_private
    volumes:
      - sessions_auth_data:/usr/src/app/.sessions_auth/
    dns:
      - 192.168.26.253
      - 8.8.8.8
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M

  flow-engine-worker:
    image: watink/backend:1.3.97
    command: ["node", "dist/src/flow-worker.js"]
    environment:
      - DB_DIALECT=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=watink
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672
    networks:
      - watink_private
    dns:
      - 192.168.26.253
      - 8.8.8.8
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  rabbitmq:
    image: rabbitmq:3-management-alpine
    networks:
      - watink_private
    dns:
      - 192.168.26.253
      - 8.8.8.8
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 512M

  postgres:
    image: ronaldodavi/pgvectorgis:latest
    environment:
      - POSTGRES_DB=watink
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - watink_private
    dns:
      - 192.168.26.253
      - 8.8.8.8
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  watink_public:
    driver: overlay
  watink_private:
    driver: overlay

volumes:
  db_data:
  sessions_auth_data:
  backend_public_data:

