services:
  plugin-manager:
    image: watink/plugin-manager:1.0.51
    build: ./plugin-manager
    environment:
      - PORT=3005
      - DATABASE_URL=postgres://postgres:postgres@watink_postgres:5432/watink?sslmode=disable
      - JWT_SECRET=3123123213123
      - FRONTEND_URL=${FRONTEND_URL:-http://app.localhost}
    networks:
      - watink_proxy
      - watink_network
    deploy:
      mode: replicated
      replicas: 1


  plugin-smtp:
    image: watink/plugin-smtp:1.0.4
    build: ./plugins/watink-smtp-go
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    networks:
      - watink_network
    deploy:
      mode: replicated
      replicas: 1

  engine-webchat:
    image: watink/engine-webchat:1.0.0
    build:
      context: ./engine-webchat
      dockerfile: ./Dockerfile
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672
      - REDIS_URL=redis://redis:6379
      - PORT=3335
    networks:
      - watink_network
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

networks:
  watink_proxy:
    external: true
    name: watink_watink_proxy
  watink_network:
    external: true
    name: watink_network
