version: '3'

networks:
  whaticket:

services:

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      - DB_DIALECT=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=${MYSQL_ROOT_PASSWORD:-strongpassword}
      - DB_NAME=${MYSQL_DATABASE:-whaticket}
      - DB_READ_HOST=${DB_READ_HOST:-postgres}
      - JWT_SECRET=${JWT_SECRET:-***REMOVED_JWT_SECRET***}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-***REMOVED_JWT_REFRESH_SECRET***}
      - BACKEND_URL=${BACKEND_URL:-http://localhost}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
      - PROXY_PORT=${PROXY_PORT:-8080}
      - CHROME_ARGS=--no-sandbox --disable-setuid-sandbox
      - AMQP_URL=${AMQP_URL:-amqp://***REMOVED_AMQP_CREDENTIALS***@rabbitmq:5672}
      - PORT=3000
    command: dockerize -wait tcp://postgres:5432 -timeout 60s && npx sequelize db:migrate && node dist/server.js
    ports:
      - ${BACKEND_PORT:-8080}:3000
    volumes:
      - ./backend/public/:/usr/src/app/public/
      - ./backend/.wwebjs_auth/:/usr/src/app/.wwebjs_auth/
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - whaticket

  frontend:
    ports:
      - ${FRONTEND_PORT:-3000}:80
      - ${FRONTEND_SSL_PORT:-3001}:443
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    environment:
      - URL_BACKEND=backend:3000
      - VITE_BACKEND_URL=${BACKEND_URL:-http://localhost}:${PROXY_PORT:-8080}/
      - VITE_HOURS_CLOSE_TICKETS_AUTO=${HOURS_CLOSE_TICKETS_AUTO}
      - FRONTEND_SERVER_NAME=${FRONTEND_SERVER_NAME}
      - BACKEND_SERVER_NAME=${BACKEND_SERVER_NAME}
    volumes:
      - ./ssl/certs/:/etc/nginx/ssl/
      - ./ssl/www/:/var/www/letsencrypt/
    networks:
      - whaticket

  postgres:
    image: ronaldodavi/pgvectorgis:latest
    volumes:
      - ./.docker/db_data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${MYSQL_DATABASE:-whaticket}
      - POSTGRES_PASSWORD=${MYSQL_ROOT_PASSWORD:-strongpassword}
      - TZ=${TZ:-America/Sao_Paulo}
    ports:
      - ${MYSQL_PORT:-5432}:5432
    restart: always
    networks:
      - whaticket

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: whaticket_rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS:-guest}
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./.docker/rabbitmq/data:/var/lib/rabbitmq/mnesia/
      - ./.docker/rabbitmq/log:/var/log/rabbitmq
    networks:
      - whaticket

  engine:
    build:
      context: ./engine-standard
      dockerfile: ./Dockerfile
    environment:
      - AMQP_URL=${AMQP_URL:-amqp://***REMOVED_AMQP_CREDENTIALS***@rabbitmq:5672}
    depends_on:
      - rabbitmq
    networks:
      - whaticket
