http:
  middlewares:
    api-strip:
      stripPrefix:
        prefixes:
          - "/api"

  routers:
    app-router:
      rule: "Host(`app.docker`)"
      service: app-service
      entryPoints:
        - web
    api-router:
      rule: "Host(`api.docker`)"
      service: api-service-go
      middlewares:
        - api-strip
      entryPoints:
        - web

  services:
    app-service:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:3000"
    api-service-node:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:8080"
    api-service-go:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:8082"
