version: "3.8"

services:
  # -------------------------------------------------------------------------
  # BACKEND (Go Core)
  # -------------------------------------------------------------------------
  painel-core:
    image: watink/panel-core:latest
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.painel-core.rule=Host(`apisaas.localhost`)"
        - "traefik.http.routers.painel-core.entrypoints=web"
        - "traefik.http.routers.painel-core.service=painel-core"
        - "traefik.http.services.painel-core.loadbalancer.server.port=8081"
        - "traefik.docker.network=watink_watink_proxy"
    environment:
      - PORT=8081
      - DB_HOST=panel_db
      - DB_USER=panel_admin
      - DB_PASS=panel_secure_pass
      - DB_NAME=panel_saas_db
      - REDIS_HOST=panel_redis:6379
      - SAAS_VAULT_KEY=change_this_in_production_to_32_byte_key
    networks:
      - panel_saas_net
      - watink_proxy
    depends_on:
      - panel_db
      - panel_redis

  # -------------------------------------------------------------------------
  # FRONTEND (React UI)
  # -------------------------------------------------------------------------
  painelui:
    image: watink/panel-ui:latest
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.painelui.rule=Host(`saas.localhost`)"
        - "traefik.http.routers.painelui.entrypoints=web"
        - "traefik.http.routers.painelui.service=painelui"
        - "traefik.http.services.painelui.loadbalancer.server.port=80"
        - "traefik.docker.network=watink_watink_proxy"
    networks:
      - panel_saas_net
      - watink_proxy

  # -------------------------------------------------------------------------
  # DATABASE (Postgres)
  # -------------------------------------------------------------------------
  panel_db:
    image: postgres:16-alpine
    volumes:
      - panel_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=panel_admin
      - POSTGRES_PASSWORD=panel_secure_pass
      - POSTGRES_DB=panel_saas_db
    networks:
      - panel_saas_net
    deploy:
      placement:
        constraints:
          - node.role == manager

  # -------------------------------------------------------------------------
  # CACHE (Redis)
  # -------------------------------------------------------------------------
  panel_redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - panel_redis_data:/data
    networks:
      - panel_saas_net

networks:
  panel_saas_net:
    driver: overlay
    attachable: true
  watink_proxy:
    external: true
    name: watink_watink_proxy

volumes:
  panel_db_data:
  panel_redis_data:
